server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: coffee-shop
  
  # Enable Virtual Threads
  threads:
    virtual:
      enabled: true
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coffee}
    username: ${DATABASE_USERNAME:coffee}
    password: ${DATABASE_PASSWORD:coffee}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:32}
      minimum-idle: 4
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        default_schema: public
    show-sql: false
    open-in-view: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: public

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-please-make-it-long-enough}
    expiration: 3600000  # 1 hour in milliseconds
    refresh-expiration: 86400000  # 24 hours

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# Application-specific Configuration
app:
  inventory:
    low-stock-threshold: 10
    restock-amount: 100
  scheduler:
    restock-check-cron: "0 0 2 * * *"  # Daily at 2 AM
  idempotency:
    ttl-hours: 24

# Logging Configuration
logging:
  level:
    root: INFO
    com.coffeeshop: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"



